import Aside from "@/components/layout/aside";
import MobileNav from "@/components/layout/mobile-nav";
import Navbar from "@/components/layout/navbar";
import Providers from "@/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SuperWager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <main className="relative">
            <Navbar />
            <div className="w-full min-h-screen p-[5%] flex gap-16 max-w-screen-2xl mx-auto mb-16 lg:mb-0">
              <div className="flex-1 lg:flex-[80%]">{children}</div>
              <Aside />
            </div>
            <MobileNav />
          </main>
        </Providers>
      </body>
    </html>
  );
}
